### PR TITLE
Content-type header check now case insensitive

### PR DESCRIPTION
**Pull request by jstruzik**
Thanks to @ccpmark for finding this bug and @mcos for finding the solution.

As stated in [RFC1341](http://www.w3.org/Protocols/rfc1341/4_Content-Type.html):

> The type, subtype, and parameter names are not case sensitive. For example, TEXT, Text, and TeXt are all equivalent.

So `application/JSON` and `ApPlICaTioN/JsOn` etc should be treated as the same during the request.

### CODE REVIEW

**Comment by Rican7** [comment]
Ooo, interesting. Good call on this one!
And thanks for the RFC reference, its great for later reference/documentation.

I knew that the header keys were case-insensitive (handled by chriso/klein.php#259 and [previously by a naive `strtolower()`](https://github.com/chriso/klein.php/blob/376fd62813eb2008f3644e206d03002a3250122a/src/Klein/DataCollection/HeaderDataCollection.php#L128-L134)), but I didn't know about the content-type field value. Good call!

**Comment by Rican7** [comment]
Merging...

**Comment by jstruzik** [comment]
:smile: tenk u!

Yeah it's interesting. There seems to be no standard for the header values, there's only various RFCs for specific headers (like "Content-Type") that define what's acceptable.

**Comment by Rican7** [comment]
Yea, strange.
Thanks again for the contribution!

**Pull request merged**
